#pragma once

#define EEPROM_SIZE 127
#define SSID_ADDR 0
#define PASS_ADDR 32
#define FLAG_ADDR 64
#define LATITUDE_ADDR 65
#define LONGITUDE_ADDR 80
#define BRIGHTNESS_ADDR 95
#define DISPLAY_MODE_ADDR 96
#define TIME_DISPLAY_DURATION_ADDR 97
#define TEMP_DISPLAY_DURATION_ADDR 99
#define LOKI_IP1_ADDR 101
#define LOKI_IP2_ADDR 104
#define LOKI_IP3_ADDR 107
#define LOKI_IP4_ADDR 110
#define LOKI_PORT_ADDR 113
#define UPDATE_PENDING_ADDR 118
#define UPDATE_ATTEMPTS_ADDR 119
#define AUTO_UPDATE_ADDR 120
#define LOKI_ENABLED_ADDR 121
